dbt_bigquery_materializations_tests:
  target: "{{ env_var('EXECUTION_CONTEXT', 'local') }}"
  outputs:
    local:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('BIGQUERY_DATASET', 'dbt_materializations_tests_local') }}"
      location: "{{ env_var('GCP_REGION', 'EU') }}"
      threads: 8
    ci:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('BIGQUERY_DATASET') }}"
      threads: 4
      keyfile: ./keyfile.json
      location: "{{ env_var('GCP_REGION') }}"
