name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dbt_version: ['1.8', '1.9', '1.10']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dbt
        working-directory: ./integration_tests
        run: |
          python -m venv ".venv${{ matrix.dbt_version }}"
          source .venv${{ matrix.dbt_version }}/bin/activate
          pip install 'dbt-core==${{ matrix.dbt_version }}.*' 'dbt-bigquery==${{ matrix.dbt_version }}.*'

      - name: Write SA Key
        run: echo "${{ secrets.GCP_TEST_SERVICE_ACCOUNT }}" | base64 --decode > keyfile.json
        working-directory: ./integration_tests

      - name: Set up environment
        run: |
          DBT_VERSION_UNDERSCORE=$(echo "${{ matrix.dbt_version }}" | sed 's/\./_/g')
          echo "BIGQUERY_DATASET=dbt_materializations_tests_ci_${DBT_VERSION_UNDERSCORE}" >> $GITHUB_ENV
        
      - name: Run dbt
        working-directory: ./integration_tests
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_REGION: ${{ secrets.GCP_REGION }}
          BIGQUERY_DATASET: ${{ env.BIGQUERY_DATASET }}
          DBT_POLICY_TAG: ${{ secrets.DBT_POLICY_TAG }}
          DBT_BIGQUERY_CONNECTION: ${{ secrets.DBT_BIGQUERY_CONNECTION }}
          GCP_TEST_BUCKET_NAME: ${{ secrets.GCP_TEST_BUCKET_NAME }}
        run: |
          source .venv${{ matrix.dbt_version }}/bin/activate
          dbt deps
          dbt build --target ci
